name = "QueerTear"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db493d974a63fb0e106efcbcfd1c0afedc5b892febea7b299aa4153f3527e8b1"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"
