name = "QueerTear"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c2628ea79fe8f31ac3cbad05e19516d54f4396bb30e0ab1e49478b6c0ba48d1"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"
