name = "QueerTear"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31ac4f472f84d60eebd8c46038b50e937c175a3118040f421fc47ebfb108df16"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
