name = "QueerTear"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8759fb68898b3a7333824ed5c7ac7eaedf3b888a564625b9dafc0d7c3d164417"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"

[options]
datapack-folder = "resourcepacks/"
