name = "QueerTear"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3301048814abde6a49dfa488767762d82385dffb3ea38f47756e059fc978ade0"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"
