name = "QueerTear"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6127b9cd7545aeb16cc3ff122046f1b15843271396becf7757eba4a5acc666c"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"
