name = "QueerTear"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0593ed67480b8e320c6f3518eb52327f759f2c7c593dfe5cd929d53aef02f521"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"
