name = "QueerTear"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c40cc5838b2d84d75295c675da7c29f2414eb2baa2eeb64adb1aba2a0b21946"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
