name = "QueerTear"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b532e189246639e9ef9e8470bc7d9cad089692eb37361b35455ecd9bdf2c73b"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
