name = "QueerTear"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "beffafab15360207d89b9adf703786b4fda891d3c093a7b13b3695702f0e0d4b"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"

[options]
datapack-folder = "resourcepacks/"
