name = "QueerTear"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bfd481ca567e28fba396b7dcd770cfdb0a8d4b35f60343957eeb04733b0f012"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"
