name = "QueerTear"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a622f095b17350c57578e9f13aa5dd5c3502a808a2cee6e96db5b63b6dc2454c"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"

[options]
datapack-folder = "resourcepacks/"
