name = "QueerTear"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c8c994b0146a772fb3ac85ea74cfb669e4073e1b012d84098933ae8d2b8db86"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"
