name = "QueerTear"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c99ce052ffa58be830581c1354fd9ed80cc4b798610c996df9e5387724d388a"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"
