name = "QueerTear"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cb85f9075d64800a9a47535bedfe5c8c25bba777a6a2289628966a295ff5e43"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"
