name = "QueerTear"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd6afc5fa0d8f7958e92a43ad8634b43090af80187b88ecbcc718169f1c6e2cd"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"

[options]
datapack-folder = "resourcepacks/"
