name = "QueerTear"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f437e5fd52673fb884d2f6761d58289b40c540a3b8f46bdb2d2cbcc296ccdca5"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
